### PR TITLE
Add consumer content API to python-rhsm

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
Rebased against master.

**Comment by kahowell** [comment]
NOTE: We should disregard python3 test results since #186 hasn't been merged yet.

**Comment by kahowell** [comment]
Made a small change to enable identification of content access certs based on the new extension, rather than product ID.

**Comment by barnabycourt** [comment]
retest this please

**Comment by barnabycourt** [comment]
test this please

**Comment by kahowell** [comment]
@cnsnyder, rebased against master, and made appropriate changes (see ce57f3e - only it has new content). Please let me know before merging, and I'll squash to a single commit.

**Pull request merged**
