### PR TITLE
[RFC] Alikins/requests wip for review

### PR DESCRIPTION
**Pull request by alikins**
Likely not ready to merge, but would like feedback on the branch.

The 'whys'
1. rhsm.connection currently uses httplib and m2crytpo as the base of it's https support.
httplib is fine, but kind of low level and unpolished. m2crypto works, but it's an extra
requirement we can potentially remove.

2. All the cool kids are using 'requests'

3. This would potentially let subman use a much saner way to setup/use connections to candlepin.
    (Although the current branch is intended to be backwards compatible, so UEPConnection() is still
    the main API entry point. subman could be updated to setup a requests.Session and/or http adapater itself, avoiding the need for passing in a dozen params to rhsm.connection)

4. python-requests uses urllib3 which has reasonable support for connection and thread pools, and
   reusing sessions (tcp keel alive, ssl session reuse, etc)

The 'why nots'
1. python-requests is a pretty high level API, and rhsm.connection needs to do some odd things, so the code ends up being fairly complicated despite using a high level API.

2. No python-requests on RHEL5, though recent RHEL6/7 versions have it.

3. It's not clear to me if python-requests proxy support is sufficient. Some of the docs indicate that
https connections through proxies are unsupported (ie, http to a proxy and 'CONNECT' to https servers, which is required for subman proxy support). I haven't tested this.

Questions for reviewers:
1. Is this useful or needed?

2. Does it work?

3. Does the code design/implementation seem reasonable?

### CODE REVIEW

**Comment by alikins** [comment]
buildbot, retest this please

**Comment by awood** [comment]
Seems reasonable.  How unreasonable would it be to jump python-rhsm to 2.0 and subscription-manager 2.0 and just dump backwards compatibility with UEPConnection?  Seems like a clean break might actually make debugging easier than having to trace back through a compatibility layer.

**Comment by alikins** [comment]
>  just dump backwards compatibility with UEPConnection? 

Not that hard I suspect, with a caveat or two.

1. Other apps use that API (virt-who, others?)
2. I suspect it would be just as easy to move all the connection/rest/http stuff from python-rhsm and into subscription-manager package, and let the network stuff in python-rhsm wither.

**Comment by alikins** [comment]
It looks like requests v 2.9.0 adds 'dir of ca bundles support'
http://docs.python-requests.org/en/latest/community/updates/#id3
RHEL7 is at 2.6 however.

It's unclear to me if current versions available to us actually support 'https through a proxy' or not.

**Comment by alikins** [comment]
The other 'meh' aspect of 'requests' is that it doesn't really gain us any async support, at least not directly.

**Comment by awood** [comment]
> It's unclear to me if current versions available to us actually support 'https through a proxy' or not.

2.6.2 at least [seems to](http://docs.python-requests.org/en/v2.6.2/user/advanced/#proxies) support it via the `HTTPS_PROXY` environment variable.  If not, I suppose we can do it ourselves with the `CONNECT` verb?  Looks like we were already doing that anyway in `connection.py` and from [what I](https://en.wikipedia.org/wiki/HTTP_tunnel) [gather](http://stackoverflow.com/a/516502/6124862) is the right way to do it.

**Pull request closed without merging**
